apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.frontend.ingress.host }}`) && PathPrefix(`{{ .Values.frontend.ingress.pathPrefix }}`)
    kind: Rule
    middlewares:
      - name: test-compress
        namespace: {{.Release.Namespace}}
    services:
    - name: frontend
      port: {{ .Values.frontend.service.port }}
